name: chat_bot
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.4+114

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dart_openai:
    path: ./pub/openai
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0
  pull_down_button: ^0.9.4
  syncfusion_flutter_sliders: ^25.1.40
  url_launcher: ^6.2.6
  dio: ^5.4.3+1
  image_picker: '1.0.8'
  extended_image: ^8.2.0
  flutter_slidable:
    git:
      url: https://github.com/letsar/flutter_slidable.git
      ref: master
  dropdown_button2: ^2.3.9
  intl: '0.19.0'
  flutter_image_compress: ^2.2.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  gal: ^2.3.0
  fluttertoast: ^8.2.5
  just_audio: ^0.9.37
  # riverpod: ^2.5.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation:
  connectivity_plus: ^6.0.2
  share_plus: '7.2.2'
  record: ^5.0.5
  logger: ^2.4.0
  responsive_framework: ^1.4.0
  pretty_dio_logger: ^1.3.1
  flutter_easyloading: ^3.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_gemini: ^2.0.3
  flutter_markdown: '0.6.20'
  loading_animation_widget: ^1.2.1
  sqflite: '2.4.0'
  sqlite3_flutter_libs: ^0.5.26
  sqflite_common_ffi:
  path: ^1.8.3
  photo_view: ^0.15.0
  animated_text_kit: ^4.2.2
  lottie: ^3.1.0
  flutter_native_splash: ^2.4.0
  screenshot: ^3.0.0
  synchronized: any
  flutter_highlighter: ^0.1.1
  json_annotation: ^4.9.0
  easy_refresh:
  freezed_annotation: ^2.4.4
  visibility_detector: ^0.4.0+2
dev_dependencies:
  freezed: ^2.5.7
  flutter_lints: ^2.0.0
  #flutter pub run flutter_launcher_icons
  flutter_launcher_icons: "^0.13.1"
  hive_generator: ^2.0.1
  build_runner:
  # the code generator
  riverpod_generator:
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint:
  # import custom_lint too as riverpod_lint depends on it
  custom_lint:
  flutter_swiper_null_safety:
  json_serializable:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/command.json
    - assets/images/
    - assets/lottie/
flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#FFFFFF"
  color_android: "#FFFFFF"
  color_dark_android: "#111111"
  color_ios: "#FFFFFF"
  color_dark_ios: "#111111"
  android_12:
    color: "#FFFFFF"
    color_dark: "#111111"
